version: '3.9'

services:
  mysql:
    image: mysql:8
    environment:
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: '0000'
      MYSQL_ROOT_PASSWORD: '0000'
    ports:
      - '3306:3306'
    volumes:
      - ./mysql-data:/var/lib/mysql
