version: '3.9'

services:
  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: '0000'
      MYSQL_ROOT_PASSWORD: '0000'
    ports:
      - '3308:3306'
    volumes:
       - ./data:/var/lib/mysql
