apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: simplsesearch-db
spec:
  replicas: 1
  serviceName: mysql
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
        - name: mysql
          image: mysql:8
          ports:
            - containerPort: 3306
          env:
            - name: MYSQL_USER
              value: "user"
            - name: MYSQL_PASSWORD
              value: "0000"
            - name: MYSQL_ROOT_PASSWORD
              value: "0000"
#          volumeMounts:
#            - name: mysql-data
#              mountPath: /var/lib/mysql
