version: '3.9'

services:
  mysql:
    image: mysql:8
    environment:
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: '0000'
      MYSQL_ROOT_PASSWORD: '0000'
    command: --init-file /init/db.sql
    ports:
      - '3306:3306'
    volumes:
      - ./init_db:/init # for bootstrapping from db.script

  redis:
    image: redis:6.2-alpine
    restart: on-failure
    ports:
      - '6379:6379'
